-- 在宝塔 MySQL 中执行此文件创建库表

CREATE DATABASE IF NOT EXISTS qsy
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE qsy;

CREATE TABLE IF NOT EXISTS counters (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  seq INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  openid VARCHAR(64) NOT NULL,
  public_id INT UNSIGNED NOT NULL,
  nickname VARCHAR(64) NOT NULL DEFAULT '',
  avatar_url VARCHAR(512) NOT NULL DEFAULT '',
  email VARCHAR(128) NOT NULL DEFAULT '',
  email_verified TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_login_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_openid (openid),
  UNIQUE KEY uk_public_id (public_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
